from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

from modules.siem_dashboard import get_siem_data
from modules.alerts import generate_alerts
from datetime import datetime


def create_pdf():

    filename = "CyberSecurity_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    story = []

    # -----------------------------
    # Title
    # -----------------------------

    story.append(Paragraph("CyberSOC Monitoring Platform", title))
    story.append(Paragraph("Cybersecurity Monitoring Report", heading))
    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            normal
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # -----------------------------
    # Summary Table
    # -----------------------------

    data = get_siem_data()

    summary = [

        ["Metric", "Value"],

        ["Hosts Scanned", str(data["hosts"])],

        ["Open Ports", str(data["ports"])],

        ["Firewall Events", str(data["firewall"])],

        ["Security Alerts", str(data["alerts"])]

    ]

    table = Table(summary, colWidths=[220,120])

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("GRID",(0,0),(-1,-1),1,colors.grey),

        ("BACKGROUND",(0,1),(-1,-1),colors.beige),

        ("BOTTOMPADDING",(0,0),(-1,0),10),

        ("ALIGN",(0,0),(-1,-1),"CENTER")

    ]))

    story.append(Paragraph("<b>Network Summary</b>", heading))

    story.append(table)

    story.append(Spacer(1,0.4*inch))

    # -----------------------------
    # Alerts
    # -----------------------------

    story.append(Paragraph("<b>Security Alerts</b>", heading))

    alerts = generate_alerts()

    if alerts:

        alert_table = [["Severity","Module","Description"]]

        for alert in alerts:

            alert_table.append([
                alert["severity"],
                alert["module"],
                alert["message"]
            ])

        table2 = Table(alert_table,colWidths=[90,120,250])

        table2.setStyle(TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.darkred),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),

            ("BOTTOMPADDING",(0,0),(-1,0),10),

            ("ALIGN",(0,0),(-1,-1),"CENTER")

        ]))

        story.append(table2)

    else:

        story.append(Paragraph("No alerts detected.", normal))

    story.append(Spacer(1,0.5*inch))

    story.append(
        Paragraph(
            "<i>Generated by CyberSOC Monitoring Platform</i>",
            normal
        )
    )

    doc.build(story)

    return filename